#时间格式 默认为 年-月-日 时:分:秒
TimeFormat: 'yyyy-MM-dd HH:mm:ss'
#强度颜色 如果修改  总长度必须为10个字符
StrengthColor: '54c6e93b2a'
#单个强度的字符
Strength: '||'
#强度石是否使用
Use: true
#UI界面
UI:
  #主界面
  Main:
    #界面标题
    Title: '&e锻造界面'
    #界面行数
    Rows: 6
    #上一页物品所在位置
    Last:
      #槽位
      Slot: 45
      #节点来自item文件夹
      Name: '上一页'
    #下一页物品所在位置
    Next:
      #槽位
      Slot: 53
      #节点来自item文件夹
      Name: '下一页'
    #图纸所占槽位
    Map: '0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44'
    #界面物品  可自行根据情况添加
    Item:
      #槽位：节点来自item文件夹
      46: '橙色玻璃板'
      47: '橙色玻璃板'
      48: '橙色玻璃板'
      49: '橙色玻璃板'
      50: '橙色玻璃板'
      51: '橙色玻璃板'
      52: '橙色玻璃板'
  #锻造界面
  Forge:
    #界面标题
    Title: '&e开始锻造'
    #界面行数
    Rows: 6
    #图纸位置
    Map: 11
    #锻造按钮
    Forge:
      Slot: 13
      #节点来自item文件夹
      Name: '锻造按钮'
    #显示强度石的位置
    StrengthItem:
      Slot: 15
      #节点来自item文件夹
      Name: '强度石所在'
    #材料所占槽位
    Material: '28,29,30,31,32,33,34,37,38,39,40,41,42,43'
    Item:
      #槽位：节点来自item文件夹
      0: '橙色玻璃板'
      1: '橙色玻璃板'
      2: '橙色玻璃板'
      3: '橙色玻璃板'
      4: '橙色玻璃板'
      5: '橙色玻璃板'
      6: '橙色玻璃板'
      7: '橙色玻璃板'
      8: '橙色玻璃板'
      9: '橙色玻璃板'
      10: '橙色玻璃板'
      12: '橙色玻璃板'
      14: '橙色玻璃板'
      16: '橙色玻璃板'
      17: '橙色玻璃板'
      18: '橙色玻璃板'
      19: '橙色玻璃板'
      20: '橙色玻璃板'
      21: '橙色玻璃板'
      22: '橙色玻璃板'
      23: '橙色玻璃板'
      24: '橙色玻璃板'
      25: '橙色玻璃板'
      26: '橙色玻璃板'
      27: '橙色玻璃板'
      35: '橙色玻璃板'
      36: '橙色玻璃板'
      44: '橙色玻璃板'
      45: '橙色玻璃板'
      46: '橙色玻璃板'
      47: '橙色玻璃板'
      48: '橙色玻璃板'
      49: '橙色玻璃板'
      50: '橙色玻璃板'
      51: '橙色玻璃板'
      52: '橙色玻璃板'
      53: '橙色玻璃板'
